<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>p2pConfigURL</key>
	<string>https://mcgi.v.qq.com/getmfomat?cmd=get_ios_config&amp;platform=iphone</string>
	<key>errorCodeConfigURL</key>
	<string>https://mcgi.v.qq.com/commdatav2?cmd=29</string>
	<key>videoSizeListURL</key>
	<string>http://vv.video.qq.com/getvfsize</string>
	<key>liveProgramVInfoURL</key>
	<string>http://info.zb.video.qq.com</string>
	<key>infoReportUrl</key>
	<string>http://mobile.video.qq.com/fcgi-bin/info_report</string>
	<key>sinaAuthorizeWithQQ</key>
	<string>https://mcgi.v.qq.com/share?dest=sina&amp;cmd=check</string>
	<key>getkeyURL</key>
	<string>http://vv.video.qq.com/getkey</string>
	<key>getvKeyURL</key>
	<string>http://vv.video.qq.com/getvkey</string>
	<key>getvbKeyURL</key>
	<string>http://vv.video.qq.com/getvbkey</string>
	<key>getinfoURL</key>
	<string>http://vv.video.qq.com/getinfo</string>
	<key>getspeedURL</key>
	<string>http://vv.video.qq.com/getspeed</string>
	<key>getbKeyURL</key>
	<string>http://vv.video.qq.com/getbkey</string>
	<key>getvinfoURL</key>
	<string>http://vv.video.qq.com/getvinfo</string>
	<key>checkTimeURL</key>
	<string>http://vv.video.qq.com/checktime</string>
	<key>getsizeURL</key>
	<string>http://vv.video.qq.com/getinfo</string>
	<key>uploadTokenURL</key>
	<string>http://sns.video.qq.com/fcgi-bin/dlib/uptoken</string>
	<key>feedbackURL</key>
	<string>http://zb.s.qq.com/reportinfo.fcgi?proxy=1</string>
	<key>sharePlayURLWithType</key>
	<string>http://m.v.qq.com/play/play.html</string>
	<key>webPlayURLWithTypeCV</key>
	<string>https://m.v.qq.com/play.html?cid={cid}&amp;type={type}&amp;vid={vid}</string>
	<key>webPlayURLWithTypeC</key>
	<string>https://m.v.qq.com/play.html?cid={cid}&amp;type={type}</string>
	<key>webPlayURLWithTypeV</key>
	<string>https://m.v.qq.com/play.html?type={type}&amp;vid={vid}&amp;title={title}</string>
	<key>webPlayURLWithChannelID</key>
	<string>https://m.v.qq.com/play.html?type={type}&amp;cnlid={cnlid}</string>
	<key>adsConfigURL</key>
	<string>https://mcgi.v.qq.com/commdatav2?cmd=36</string>
	<key>liveShareURL</key>
	<string>http://m.v.qq.com/live.html</string>
	<key>liveTVStationShareURL</key>
	<string>http://m.v.qq.com/live.html</string>
	<key>defaultPlaybackServerUrl</key>
	<string>http://video.dispatch.tc.qq.com</string>
	<key>momentUploadPhotoURL</key>
	<string>https://vgps.video.qq.com/picStoreSrv/picUpload</string>
	<key>momentVideoTimelineURL</key>
	<string>http://vg.video.qq.com/domain/timeline/video_timeline</string>
	<key>momentVideoLikeURL</key>
	<string>http://vg.video.qq.com/domain/timeline/video_like</string>
	<key>momentToUserIDURL</key>
	<string>http://vg.video.qq.com/domain/user/msgid2uin</string>
	<key>userHelpUrl</key>
	<string>https://m.v.qq.com/x/app/help/index.html</string>
    <key>iapVisitorBindUINURL</key>
    <string>http://p30.video.qq.com/fcgi-bin/trans_guidvip_to_uin</string>
    <key>banabaBarrageFromWebClientURL</key>
    <string>http://bullet.video.qq.com/fcgi-bin</string>
	<key>banabaBarrageURL</key>
	<string>http://mfm.video.qq.com</string>
	<key>unicomBaseUrl</key>
	<string>http://114.255.201.238:8090/video</string>
	<key>unicomCheckUserIp</key>
	<string>https://mcgi.v.qq.com/unicom/check_user_ip</string>
	<key>unicomCheckUserOrder</key>
	<string>https://mcgi.v.qq.com/unicom/check_user_order</string>
	<key>unicomGetvinfoURL</key>
	<string>http://vv.video.qq.com/getvinfo</string>
	<key>unicomGetvKeyURL</key>
	<string>http://vv.video.qq.com/getvkey</string>
	<key>unicomGetvbKeyURL</key>
	<string>http://vv.video.qq.com/getvbkey</string>
    <key>telecomBaseUrl</key>
    <string>http://open.e.189.cn/api/account/gateway.do</string>
	<key>videoTipsURL</key>
	<string>http://vg.video.qq.com/domain/tips/video_tips</string>
	<key>drawingResourceURL</key>
	<string>http://vgps.video.qq.com:8002/graffiti</string>
	<key>visitorGiveTicketURL</key>
	<string>http://p30.video.qq.com/fcgi-bin/ykgiveticket</string>
	<key>unicomH5BaseUrl</key>
	<string>https://m.v.qq.com/activity/wo/free.html</string>
	<key>interactiveVoteH5URL</key>
	<string>https://m.v.qq.com/activity/qqvideo/interact/live.html</string>
	<key>hollywoodLoginPrivacyURL</key>
	<string>https://m.v.qq.com/about/privacy.html</string>
	<key>hollywoodQQRegisterURL</key>
	<string>https://ssl.zc.qq.com/chs/index.html</string>
	<key>starThemeDiyURL</key>
	<string>http://www.qq.com</string>
	<key>starThemeShareURL</key>
	<string>http://m.v.qq.com/activity/star/star.html?starthemeid=</string>
	<key>appLiveCommentUploadPhoto</key>
	<string>https://upload.coral.qq.com/image/upload</string>
	<key>liveToolH5EffectURL</key>
	<string>https://m.v.qq.com/activity/qqvideo/effect/H5Effect.html</string>
	<key>appPropsUploadPhotoURL</key>
	<string>https://upload.coral.qq.com/image/upload</string>
	<key>JCEServiceURL</key>
	<string>http://preoma.video.qq.com</string>
	<key>dlnaIntroURL</key>
	<string>https://m.v.qq.com/about/cast-tv.html</string>
    <key>dlnaIntroURL2</key>
    <string>https://tv.video.qq.com/weixinact/Wechat/projection/dlna</string>
    <key>pppIntroURL</key>
    <string>https://tv.video.qq.com/airplay/tpl/phoneguide</string>
	<key>Ranklist15ShareURL</key>
	<string>https://m.v.qq.com/activity/utopia/toplist.html</string>
	<key>propertyIntroURL</key>
	<string>https://m.v.qq.com/about/coin.html</string>
    <key>logReportTaskURL</key>
    <string>http://ctask.witil.qq.com/php/getchecktask.php?</string>
    <key>iapPayTypeConfigURL</key>
    <string>https://pay.video.qq.com/fcgi-bin/iaptype</string>
    <key>commonH5EntryUrl</key>
    <string>http://m.v.qq.com/free_flow/index.html?_bid=28</string>
    <key>telecomH5URL</key>
    <string>https://chong.qq.com/mobile/traffic_tcvideo_test.shtml</string>
    <key>PrivateSettingUrl</key>
    <string>https://m.v.qq.com/about/privacy-policy.html</string>
    <key>StarThemeHomeUrl</key>
    <string>https://m.v.qq.com/startheme/index.html?_bid=20</string>
    <key>MyTicketUrl</key>
    <string>https://m.v.qq.com/ticket/myticket.html?_bid=17</string>
    <key>CacheListiPadTipsActionURL</key>
    <string>https://cy.qq.com/p/caiyun/2097.html?ptag=phone_dl_prom</string>
</dict>
</plist>
